[package]
name = "fsm_timers_std"
version = "0.1.0"
authors = ["Rudi Benkovic <rudi.benkovic@gmail.com>"]

[dependencies]
futures = "0.1.17"
tokio-timer = "0.1.2"
fsm = {path="../"}

[dev-dependencies]
fsm_codegen = { path="../fsm_codegen/" }
